architect:
  - myunusov
docker:
  image: "teamed/docker-java-8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -Penv-prod
    mvn clean site site:site -Penv-prod,site,gh-pages
