architect:
  - myunusov
docker:
  image: "maxur/maxur-dev"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"

site:
  script: |
  mvn site com.github.github:site-maven-plugin:site --settings /home/r/settings.xml -Denv=prod -Psite,self-doc,debug
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -Denv=prod
    git commit -am "${tag}"
    mvn site com.github.github:site-maven-plugin:site --settings /home/r/settings.xml -Denv=prod -Psite,self-doc,debug
    mvn clean deploy --settings /home/r/settings.xml -Denv=prod -Pmaxur-base,sonatype,debug
