architect:
  - myunusov
docker:
  image: "teamed/docker-java-8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -Denv=prod
    git commit -am "${tag}"
    mvn site com.github.github:site-maven-plugin:site --settings /home/r/settings.xml -e -X -Denv=prod -Psite,self-doc,gh-pages,debug
    mvn clean deploy --settings /home/r/settings.xml -e -X -Denv=prod -Pmaxur-base,sonatype,site,self-doc,gh-pages,debug
